# Generated by Django 3.0.4 on 2020-07-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_topic_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
